require("dotenv").config();
const express = require("express");
const cors = require("cors");
const { Server } = require("@modelcontextprotocol/sdk/server/index.js");
const { SSEServerTransport } = require("@modelcontextprotocol/sdk/server/sse.js");
const { CallToolRequestSchema, ListToolsRequestSchema } = require("@modelcontextprotocol/sdk/types.js");
const { runAegisPipeline } = require("./orchestrator/pipeline");

const app = express();
app.use(cors());

// Initialize the MCP server
const server = new Server({
  name: "aegis-mcp-server",
  version: "1.0.0",
}, {
  capabilities: { tools: {} }
});

// Define the AEGIS pipeline as an MCP Tool
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "run_aegis_pipeline",
        description: "Runs the complete Autonomous Examination Guardian & Intelligence System (AEGIS) multi-agent clinical pipeline on a patient's medical chart. Returns a synthesized, conflict-free clinical consensus including drug safety alerts, missed diagnoses, billing compliance, and prior authorization drafts.",
        inputSchema: {
          type: "object",
          properties: {
            clinical_note: {
              type: "string",
              description: "The raw clinical text or patient chart (e.g., HPI, PMH, Vitals, Medications)."
            }
          },
          required: ["clinical_note"]
        }
      }
    ]
  };
});

// Handle tool execution
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === "run_aegis_pipeline") {
    try {
      const { clinical_note } = request.params.arguments;
      if (!clinical_note) throw new Error("clinical_note argument is required");
      
      console.log(`[MCP] Executing AEGIS pipeline for incoming clinical note...`);
      const result = await runAegisPipeline(clinical_note, null); // null for image data
      
      // Formatting the final Arbiter report as text
      const reportText = `
# AEGIS ARBITER CONSENSUS REPORT

## Guardian (Safety Checks)
Risk Level: ${result.guardian.riskLevel}
Summary: ${result.guardian.summary}

## Sentinel (Missed Diagnoses)
Status: ${result.sentinel.status}
Summary: ${result.sentinel.summary}

## Compliance (ICD-10 & Billing)
Status: ${result.compliance.status}
Summary: ${result.compliance.summary}

## Advocate (Prior Authorization)
Status: ${result.advocate.status}
Recommendation: ${result.advocate.recommendation}

## Final Arbiter Decision
${result.arbiter.finalDecision}

---
*Generated by AEGIS Multi-Agent System via MCP*
`;

      return {
        content: [
          {
            type: "text",
            text: reportText
          }
        ]
      };
    } catch (e) {
      console.error("[MCP] Tool error:", e);
      return {
        isError: true,
        content: [{ type: "text", text: `AEGIS Pipeline Error: ${e.message}` }]
      };
    }
  }
  
  throw new Error(`Tool not found: ${request.params.name}`);
});

// Setup SSE Transport
// We manage active transports per request to support multi-session concurrency safely
const activeTransports = new Map();

app.get("/sse", async (req, res) => {
  console.log("[MCP] New SSE connection established");
  const transport = new SSEServerTransport("/message", res);
  const sessionId = Math.random().toString(36).substring(7);
  activeTransports.set(sessionId, transport);
  
  // Attach session ID to response headers so client knows where to POST
  res.setHeader("X-Session-ID", sessionId);
  
  await server.connect(transport);
  
  req.on('close', () => {
    console.log(`[MCP] SSE connection closed (session: ${sessionId})`);
    activeTransports.delete(sessionId);
  });
});

app.post("/message", express.json(), async (req, res) => {
  // To handle multiple clients, ideally Prompt Opinion sends the session ID.
  // If not, we fallback to the most recent/only transport for simpler hackathon setups.
  const sessionId = req.headers["x-session-id"];
  let transport = sessionId ? activeTransports.get(sessionId) : Array.from(activeTransports.values()).pop();
  
  if (!transport) {
    res.status(400).send("No active SSE connection");
    return;
  }
  await transport.handlePostMessage(req, res);
});

// Start the server
const PORT = process.env.MCP_PORT || 4000;
app.listen(PORT, () => {
  console.log(`[MCP] AEGIS MCP Server running on http://localhost:${PORT}`);
  console.log(`[MCP] -> Connect Prompt Opinion client to SSE endpoint: http://localhost:${PORT}/sse`);
});
